name: Build binaries

on:
  push:
    branches: ['master']
    
jobs:
  build:
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-musl,  aarch64-unknown-linux-musl, universal2-apple-darwin, x86_64-pc-windows-gnu ]

    runs-on: ubuntu-22.04
    container:
      image: messense/cargo-zigbuild
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mingw
        if: ${{ contains(matrix.target, 'windows') }}
        run: apt update && apt install -y mingw-w64

      - name: Build binary for ${{ matrix.target }}
        run: cargo zigbuild --release --target ${{ matrix.target }}

      - name: Archive binary
        run: tar -cvf kodjin-cli-${{ matrix.target }}.tar -C target/${{ matrix.target }}/release kodjin-cli

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kodjin-cli-${{ matrix.target }}
          path: kodjin-cli-${{ matrix.target }}.tar

  create-release:
    needs: build
    runs-on: ubuntu-22.04
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts/

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          removeArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: "downloaded-artifacts/*/*"
          body: ${{ github.event.head_commit.message }}
          prerelease: true
          name: Nightly release
          tag: nightly

      - name: Update the nightly tag
        run: |
          git tag -f nightly
          git push -f origin nightly
        shell: bash
