name: Build binaries

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: messense/cargo-zigbuild:0.20.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
          apt update 
          apt install -y mingw-w64 goreleaser

      - name: Set up build cache
        uses: Swatinem/rust-cache@v2

      - name: Build and release
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
